// Java/Udemy/Go Full Stack with Spring Boot and Angular 7/todo/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoDataService } from '../service/data/todo-data.service';
import { Todo } from '../list-todos/list-todos.component';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {

  id: number;
  todo: Todo;

  constructor(
    private todoService: TodoDataService,
    private route: ActivatedRoute,
    private router: Router
  ) { }

  ngOnInit() {
    this.id = this.route.snapshot.params['id'];
    this.todo = new Todo(this.id, '', false, new Date());
    
    if (this.id != -1) {
      this.todoService.retrieveTodo('dvt32', this.id).subscribe(
        data => {
          this.todo = data;
        }
      );
    }
  }

  saveTodo() {
    if (this.id == -1) {
      this.todoService.createTodo('dvt32', this.todo).subscribe(
        data => {
          console.log(data);
          this.router.navigate(['todos']);
        }
      );
    }
    else {
      this.todoService.updateTodo('dvt32', this.id, this.todo).subscribe(
        data => {
          console.log(data);
          this.router.navigate(['todos']);
        }
      );
    }
  }

}

<h1>Todo</h1>

<div class="container">
  <div class="alert alert-warning" *ngIf="todoForm.dirty && todoForm.invalid">Enter valid values!</div>
  <div class="alert alert-warning" *ngIf="todoForm.dirty && targetDate.invalid">Enter valid target date!</div>
  <div class="alert alert-warning" *ngIf="todoForm.dirty && description.invalid">Enter at least 5 characters in description!</div>

  <form (ngSubmit)="!todoForm.invalid && saveTodo()" #todoForm="ngForm">
    <fieldset class="form-group">
      <label>Description</label>
      <input 
        type="text" 
        #description="ngModel" 
        [(ngModel)]="todo.description" 
        class="form-control" 
        name="description" 
        required="required" 
        minlength="5"
      >
    </fieldset>

    <fieldset class="form-group">
      <label>Target Date</label>
      <input 
        type="date" #targetDate="ngModel"
        [ngModel]="todo.targetDate | date: 'yyyy-MM-dd'"
        (ngModelChange)="todo.targetDate = $event" 
        class="form-control" 
        name="targetDate" 
        required="required"
      >
    </fieldset>

    <button type="submit" class="btn btn-success">Save</button>
  </form>

</div>

// Java/Udemy/Go Full Stack with Spring Boot and React/todo-app/src/components/todo/TodoComponent.jsx
import React, { Component } from 'react'
import moment from 'moment';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import TodoDataService from '../../api/todo/TodoDataService';
import AuthenticationService from './AuthenticationService';

export default class TodoComponent extends Component {

    constructor(props) {
        super(props);
        this.state = {
            id: this.props.match.params.id,
            description: "",
            targetDate: moment( new Date() ).format('YYYY-MM-DD')
        };
        this.onSubmit = this.onSubmit.bind(this);
        this.validate = this.validate.bind(this);
    }

    componentDidMount() {
        if (this.state.id === -1) {
            return;
        }
        
        let username = AuthenticationService.getLoggedInUserName();
        TodoDataService.retrieveTodo(username, this.state.id).then(
            response => this.setState(
                {
                    description: response.data.description,
                    targetDate: moment(response.data.targetDate).format('YYYY-MM-DD')
                }
            )
        );
    }

    validate(values) {
        let errors = {};

        if (!values.description) {
            errors.description = "Enter a description!";
        }
        else if (values.description.length < 5) {
            errors.description = "Enter at least 5 characters in description!";
        }

        if ( !moment(values.targetDate).isValid() ) {
            errors.targetDate = "Enter a valid target date!";
        }

        return errors;
    }

    onSubmit(values /* passed values from form */) {
        let username = AuthenticationService.getLoggedInUserName();

        let todo = {
            id: this.state.id,
            description: values.description,
            targetDate: values.targetDate
        };

        if (this.state.id === -1) {
            TodoDataService.createTodo(username, todo).then(
                () => {
                    this.props.history.push('/todos');
                }
            );
        }
        else {
            TodoDataService.updateTodo(username, this.state.id, todo).then(
                () => {
                    this.props.history.push('/todos');
                }
            );
        }  
    }

    render() {
        let { description, targetDate } = this.state;

        return (
            <div>
                <h1>Todo</h1>
                <div className="container">
                    <Formik
                        initialValues={ {description, targetDate} }
                        onSubmit={this.onSubmit}
                        validateOnChange={false}
                        validateOnBlur={false}
                        validate={this.validate}
                        enableReinitialize={true}
                    >
                        {
                            (props) => (
                                <Form>
                                    <ErrorMessage 
                                        name="description" 
                                        component="div" 
                                        className="alert alert-warning" 
                                    />
                                    <ErrorMessage 
                                        name="targetDate" 
                                        component="div" 
                                        className="alert alert-warning" 
                                    />
                                    <fieldset className="form-group">
                                        <label>Description</label>
                                        <Field className="form-control" type="text" name="description" />
                                    </fieldset>
                                    <fieldset className="form-group">
                                        <label>Target Date</label>
                                        <Field className="form-control" type="date" name="targetDate" />
                                    </fieldset>
                                    <button className="btn btn-success" type="submit">Save</button>
                                </Form>
                            )
                        }
                    </Formik>
                </div>
            </div>
        )
    }

}
