// Java/Udemy/Go Full Stack with Spring Boot and Angular 7/todo/src/app/welcome/welcome.component.ts
import { Component, OnInit } from '@angular/core';
import { AppComponent } from '../app.component';
import { ActivatedRoute } from '@angular/router';
import { WelcomeDataService } from '../service/data/welcome-data.service';

@Component({
  selector: 'app-welcome',
  templateUrl: './welcome.component.html',
  styleUrls: ['./welcome.component.css']
})
export class WelcomeComponent implements OnInit { // export = public class
  message: string = 'Some Welcome Message';
  welcomeMessageFromService: string;
  name = '';

  constructor(
    private route: ActivatedRoute,
    private service: WelcomeDataService) 
  { 

  }

  ngOnInit() : void {
    // console.log(this.message);
    // console.log( this.route.snapshot.params['name'] );
    this.name = this.route.snapshot.params['name'];
  }

  getWelcomeMessage() {
    // console.log( this.service.executeHelloWorldBeanService() );
    
    this.service.executeHelloWorldBeanService().subscribe(
      response => this.handleSuccessfulResponse(response),
      error => this.handleErrorResponse(error)
    );

    // console.log('last line of getWelcomeMessage');

    // console.log("welcome message");
  }

  getWelcomeMessageWithParameter() {
    // console.log( this.service.executeHelloWorldBeanService() );
    
    this.service.executeHelloWorldBeanServiceWithPathVariable(this.name).subscribe(
      response => this.handleSuccessfulResponse(response),
      error => this.handleErrorResponse(error)
    );

    // console.log('last line of getWelcomeMessage');

    // console.log("welcome message");
  }

  handleSuccessfulResponse(response) {
    this.welcomeMessageFromService = response.message;
    // console.log(response);
    // console.log(response.message);
  }

  handleErrorResponse(error) {
    // console.log(error);
    // console.log(error.error);
    // console.log(error.error.message);
    this.welcomeMessageFromService = error.error.message;
  }
}

export class Class1 {}
export class Class2 {}

<h1>Welcome!</h1>

<div class="container">
    Welcome, {{name}}!
    You can manage your todos <a routerLink="/todos">here</a>!
</div>

<div class="container">
    Click here to get a customized message!
    <button (click)="getWelcomeMessageWithParameter()" class="btn btn-success">Get Welcome Message</button>
</div>

<div class="container" *ngIf="welcomeMessageFromService">
    <h2>Your Customized Welcome Message</h2>
    {{welcomeMessageFromService}}
</div>

// Java/Udemy/Go Full Stack with Spring Boot and React/todo-app/src/components/todo/WelcomeComponent.jsx
import React, { Component } from 'react'
import { Link } from 'react-router-dom';
import HelloWorldService from '../../api/todo/HelloWorldService';

class WelcomeComponent
    extends Component
{
    
    constructor(props) {
        super(props);
        this.retrieveWelcomeMessage = this.retrieveWelcomeMessage.bind(this);
        this.state = {
            welcomeMessage: ""
        };
        this.handleSuccessfulResponse = this.handleSuccessfulResponse.bind(this);
        this.handleError = this.handleError.bind(this);
    }

    render() {
        return (
            <>
                <h1>Welcome!</h1>
                
                <div className="container">
                    Welcome, {this.props.match.params.name}! 
                    You can manage your <Link to="/todos">todos</Link> here.
                </div>

                <div className="container">
                    Click here to get a customized welcome message.
                    <button onClick={this.retrieveWelcomeMessage} className="btn btn-success">Get Welcome Message</button>
                </div>

                <div className="container">
                    { this.state.welcomeMessage }
                </div>
            </>
        );
    }

    retrieveWelcomeMessage() {
        // HelloWorldService.executeHelloWorldService().then(
        //     response => this.handleSuccessfulResponse(response)
        // );

        // HelloWorldService.executeHelloWorldBeanService().then(
        //     response => this.handleSuccessfulResponse(response)
        // );

        HelloWorldService.executeHelloWorldPathVariableService(this.props.match.params.name)
        .then(
            response => this.handleSuccessfulResponse(response)
        )
        .catch(
            error => this.handleError(error)
        );
    }

    handleSuccessfulResponse(response) {
        this.setState(
            {
                welcomeMessage: response.data.message
            }
        );
    }

    handleError(error) {
        let errorMessage = '';

        if (error.message) {
            errorMessage += error.message;
        }

        if (error.response && error.response.data) {
            errorMessage += error.response.data.message;
        }

        this.setState(
            {
                welcomeMessage: errorMessage
            }
        );
    }
}

export default WelcomeComponent;
