// Java/Udemy/Go Full Stack with Spring Boot and React/todo-app/src/components/todo/LoginComponent.jsx
import React, { Component } from 'react'
import AuthenticationService from './AuthenticationService'

class LoginComponent
    extends Component
{
    constructor(props) {
        super(props);
        this.state = {
            username: 'dvt32',
            password: '',
            hasLoginFailed: false,
            showSuccessMessage: false
        }
        // this.handleUsernameChange = this.handleUsernameChange.bind(this);
        // this.handlePasswordChange = this.handlePasswordChange.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.loginClicked = this.loginClicked.bind(this);
    }

    // handleUsernameChange(event) {
    //     this.setState(
    //         {
    //             username: event.target.value
    //         }
    //     );
    // }

    // handlePasswordChange(event) {
    //     this.setState(
    //         {
    //             password: event.target.value
    //         }
    //     );
    // }

    handleChange(event) {
        // console.log(this.state);
        this.setState(
            {
                [event.target.name]: event.target.value
            }
        );
    }

    loginClicked() {
        // if (this.state.username === "dvt32" && this.state.password === "1234") {
        //     AuthenticationService.registerSuccessfulLogin( this.state.username, this.state.password );
        //     this.props.history.push(`/welcome/${this.state.username}`);
        //     // this.setState( {showSuccessMessage: true} );
        //     // this.setState( {hasLoginFailed: false} );
        // }
        // else {
        //     this.setState( {showSuccessMessage: false} );
        //     this.setState( {hasLoginFailed: true} );
        // }

        /*
        AuthenticationService.executeBasicAuthenticationService(this.state.username, this.state.password)
        .then(
            () => {
                AuthenticationService.registerSuccessfulLogin( this.state.username, this.state.password );
                this.props.history.push(`/welcome/${this.state.username}`);
            }
        )
        .catch(
            () => {
                this.setState( {showSuccessMessage: false} );
                this.setState( {hasLoginFailed: true} );
            } 
        );
        */

        AuthenticationService.executeJwtAuthenticationService(this.state.username, this.state.password)
        .then(
            (response) => {
                AuthenticationService.registerSuccessfulLoginForJwt( this.state.username, response.data.token );
                this.props.history.push(`/welcome/${this.state.username}`);
            }
        )
        .catch(
            () => {
                this.setState( {showSuccessMessage: false} );
                this.setState( {hasLoginFailed: true} );
            } 
        );
    }

    render() {
        return (
            <div>
                <h1>Login</h1>
                <div className="container">
                    {/* <ShowInvalidCredentials hasLoginFailed={this.state.hasLoginFailed} />
                    <ShowLoginSuccessMessage showSuccessMessage={this.state.showSuccessMessage} /> */}
                    
                    { this.state.hasLoginFailed && <div className="alert alert-warning">Invalid Credentials</div> }
                    { this.state.showSuccessMessage && <div>Login Successful</div> }

                    User Name: <input type="text" name="username" value={this.state.username} onChange={this.handleChange} />
                    Password: <input type="password" name="password" value={this.state.password} onChange={this.handleChange} />
                    
                    <button className="btn btn-success" onClick={this.loginClicked}>Login</button>
                </div>
            </div>
        );
    }
}

export default LoginComponent;

// Java/Udemy/Go Full Stack with Spring Boot and Angular 7/todo/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HardcodedAuthenticationService } from '../service/hardcoded-authentication.service';
import { BasicAuthenticationService } from '../service/basic-authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  username = 'dvt32';
  password = '123';
  errorMessage = 'Invalid Credentials';
  invalidLogin = false;

  constructor(
    private router: Router,
    private hardcodedAuthenticationService: HardcodedAuthenticationService,
    private basicAuthenticationService: BasicAuthenticationService) 
  { 

  }

  ngOnInit() {
  }

  handleLogin() {
    if (this.hardcodedAuthenticationService.authenticate(this.username, this.password)) {
      this.router.navigate(['welcome', this.username]);
      this.invalidLogin = false;
    }
    else {
      this.invalidLogin = true;
    }
    // console.log(this.username);
  }

  handleBasicAuthLogin() {
    this.basicAuthenticationService.executeAuthenticationService(this.username, this.password).subscribe(
      data => {
        console.log(data);
        this.router.navigate(['welcome', this.username]);
        this.invalidLogin = false;
      },
      error => {
        console.log(error);
        this.invalidLogin = true;
      }
    );
  }

  handleJwtAuthLogin() {
    this.basicAuthenticationService.executeJwtAuthenticationService(this.username, this.password).subscribe(
      data => {
        console.log(data);
        this.router.navigate(['welcome', this.username]);
        this.invalidLogin = false;
      },
      error => {
        console.log(error);
        this.invalidLogin = true;
      }
    );
  }
  
}

<h1>Login</h1>

<div class="container">
    <div class="alert alert-warning" *ngIf='invalidLogin'>{{errorMessage}}</div>
    <div>
        User Name : <input type="text" name="username" [(ngModel)]="username" />
        Password : <input type="password" name="password" [(ngModel)]="password" />  
        <!-- <button (click)=handleLogin() class="btn btn-success">Login</button> -->
        <button (click)=handleJwtAuthLogin() class="btn btn-success">Login</button>
    </div>
</div>
