// Java/Udemy/Go Full Stack with Spring Boot and React/todo-app/src/components/todo/ListTodosComponent.jsx
import React, { Component } from 'react'
import TodoDataService from '../../api/todo/TodoDataService';
import AuthenticationService from './AuthenticationService';
import moment from 'moment';

class ListTodosComponent
    extends Component
{
    constructor(props) {
        super(props);
        this.state = {
            todos: [],
            message: null
        };

        this.deleteTodoClicked = this.deleteTodoClicked.bind(this);
        this.addTodoClicked = this.addTodoClicked.bind(this);
        this.updateTodoClicked = this.updateTodoClicked.bind(this);
        this.refreshTodos = this.refreshTodos.bind(this);
    }

    componentDidMount() {
        this.refreshTodos();
    }
    
    refreshTodos() {
        let username = AuthenticationService.getLoggedInUserName();
        TodoDataService.retrieveAllTodos(username)
        .then(
            response => {
                this.setState(
                    {
                        todos: response.data
                    }
                );
            }
        );
    }

    deleteTodoClicked(id) {
        let username = AuthenticationService.getLoggedInUserName();
        
        TodoDataService.deleteTodo(username, id).then(
            response => {
                this.setState(
                    {
                        message: `Todo with ID ${id} successfully deleted!`
                    }
                );
                this.refreshTodos();
            }
        );
    }

    updateTodoClicked(id) {
        this.props.history.push(`/todos/${id}`);

        // let username = AuthenticationService.getLoggedInUserName();
        
        // TodoDataService.deleteTodo(username, id).then(
        //     response => {
        //         this.setState(
        //             {
        //                 message: `Todo with ID ${id} successfully deleted!`
        //             }
        //         );
        //         this.refreshTodos();
        //     }
        // );
    }

    addTodoClicked() {
        this.props.history.push(`/todos/-1`);
    }

    render() {
        return (
            <div>
                <h1>List Todos</h1>
                {this.state.message && <div className="alert alert-success">{ this.state.message }</div>}
                <div className="container">
                    <table className="table">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th>Is Completed?</th>
                                <th>Target Date</th>
                                <th>Update</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            {
                                this.state.todos.map(
                                    todo =>
                                        <tr key={ todo.id }>
                                            <td>{ todo.description }</td>
                                            <td>{ todo.done.toString() }</td>
                                            <td>{ moment(todo.targetDate).format('YYYY-MM-DD') }</td>
                                            <td>
                                                <button 
                                                    className="btn btn-success" 
                                                    onClick={ () => this.updateTodoClicked(todo.id) }
                                                >
                                                    Update
                                                </button>
                                            </td>
                                            <td>
                                                <button 
                                                    className="btn btn-warning" 
                                                    onClick={ () => this.deleteTodoClicked(todo.id) }
                                                >
                                                    Delete
                                                </button>
                                            </td>
                                        </tr>
                                )
                            }
                        </tbody>
                    </table>

                    <div className="row">
                        <button className="btn btn-success" onClick={this.addTodoClicked}>Add</button>
                    </div>

                </div>
            </div>
        );
    }

}

export default ListTodosComponent;

// Java/Udemy/Go Full Stack with Spring Boot and Angular 7/todo/src/app/list-todos/list-todos.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoDataService } from '../service/data/todo-data.service';
import { Router } from '@angular/router';

export class Todo {
  constructor(
    public id: number,
    public description: string,
    public done: boolean,
    public targetDate: Date
  ) {
    
  }
}

@Component({
  selector: 'app-list-todos',
  templateUrl: './list-todos.component.html',
  styleUrls: ['./list-todos.component.css']
})
export class ListTodosComponent implements OnInit {

  todos: Todo[];
  // = [
  //   new Todo(1, 'Learn to Dance', false, new Date()),
  //   new Todo(2, 'Become an Expert at Angular', false, new Date()),
  //   new Todo(3, 'Visit Bulgaria', false, new Date())
  //   // { id: 1, description: 'Learn to Dance' },
  //   // { id: 2, description:  },
  //   // { id: 3, description:  }
  // ];

  // todo = {
  //   id: 1,
  //   description: 'Learn to Dance'
  // };

  message: string;

  constructor(
    private todoService: TodoDataService,
    private router: Router
  ) { }

  ngOnInit() {
    this.refreshTodos();
  }

  refreshTodos() {
    this.todoService.retrieveAllTodos('dvt32').subscribe(
      response => {
        console.log(response);
        this.todos = response;
      }
    );
  }

  deleteTodo(id) {
    console.log(`delete todo ${id}`);
    this.todoService.deleteTodo('dvt32', id).subscribe(
      response => {
        console.log(response);
        this.message = `Successfully deleted todo ${id}!`;
        this.refreshTodos();
      }
    );
  }

  updateTodo(id) {
    console.log(`update todo ${id}`);
    this.router.navigate(['todos', id]);
  }

  addTodo() {
    this.router.navigate(['todos', -1]);
  }
}

<h1>My Todos</h1>

<div class="alert alert-success" *ngIf='message'>{{message}}</div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>Description</th>
        <th>Target Date</th>
        <th>Is Completed?</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let todo of todos">
        <td>{{todo.description}}</td>
        <td>{{todo.targetDate | date | uppercase}}</td>
        <td>{{todo.done}}</td>
        <td><button (click)="updateTodo(todo.id)" class="btn btn-success">Update</button></td>
        <td><button (click)="deleteTodo(todo.id)" class="btn btn-warning">Delete</button></td>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <td><button (click)="addTodo()" class="btn btn-success">Add</button></td>
  </div>
</div>
